### ISSUE TITLE
Envious Causes a CTD

### ISSUE THREAD

**Issue by Dicktatorship** [ReinaSHSL/Yohane-#12]
## Expected Behavior
Card Envious Copies Enemy Buffs and Debuffs

## Actual Behavior
When used on an enemy with the curl up buff (gain defense on hit) the game crashes to desktop

## Steps to Reproduce the Problem

  1.Use envious

**Comment by timeracers** [comment]
Your usage of the format is a little off.
## Expected Behavior
Envious copies curl up from the target
## Actual Behavior
The game crashes instead
## Steps to Reproduce the Problem
1. Use envious on enemy with curl up

Also if you enable the debug flag in ModTheSpire you can get what exception caused the crash which is very useful information.

**Comment by ReinaSHSL** [comment]
fIXED
